---
- name: Docker | Start Installation Docker
  include: install-docker.yml

- name: Docker | Ensure service started
  service: name=docker state=started

- name: Docker | Validate Docker
  shell: docker run hello-world

- name: Docker | Docker Compose | Validate version
  shell: /usr/local/bin/docker-compose version
